### ISSUE TITLE
broken on python 3.13

### ISSUE THREAD

**Issue by edsu** [edsu/htmldiff2#5]
```
$ python test.py
Traceback (most recent call last):
  File "/Users/edsu/Projects/htmldiff2/test.py", line 2, in <module>
    import htmldiff2
  File "/Users/edsu/Projects/htmldiff2/htmldiff2.py", line 37, in <module>
    _leading_space_re = re.compile(r'^(\s+)(?u)')
  File "/Users/edsu/.pyenv/versions/3.13.0/lib/python3.13/re/__init__.py", line 289, in compile
    return _compile(pattern, flags)
  File "/Users/edsu/.pyenv/versions/3.13.0/lib/python3.13/re/__init__.py", line 350, in _compile
    p = _compiler.compile(pattern, flags)
  File "/Users/edsu/.pyenv/versions/3.13.0/lib/python3.13/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
  File "/Users/edsu/.pyenv/versions/3.13.0/lib/python3.13/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/Users/edsu/.pyenv/versions/3.13.0/lib/python3.13/re/_parser.py", line 459, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                       not nested and not items))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edsu/.pyenv/versions/3.13.0/lib/python3.13/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
                       'of the expression',
                       source.tell() - start)
re.PatternError: global flags not at the start of the expression at position 6
```

This error actually gets thrown when loading the module!

**Comment by edsu** [comment]
Closed by #6
